extends RefCounted
## Shared UI skin: riveted-metal 9-patch panels and buttons generated by
## tools/generate_ps1_sprites.gd. Call UiTheme.make() and assign to the root
## Control (also set its texture_filter to NEAREST so the patches stay chunky).

const TEXTURE_MARGIN := 15.0  # 5 logical px at the 3x sprite scale

static var _theme: Theme


static func make() -> Theme:
	if _theme != null:
		return _theme
	_theme = Theme.new()
	# Tile the panel's stretch zones: its grime stays pixel-scale on any size.
	var panel_box := _box("res://assets/sprites/ui_panel.png", 18.0)
	panel_box.axis_stretch_horizontal = StyleBoxTexture.AXIS_STRETCH_MODE_TILE
	panel_box.axis_stretch_vertical = StyleBoxTexture.AXIS_STRETCH_MODE_TILE
	_theme.set_stylebox("panel", "PanelContainer", panel_box)
	_theme.set_stylebox("normal", "Button", _box("res://assets/sprites/ui_button.png"))
	_theme.set_stylebox("hover", "Button", _box("res://assets/sprites/ui_button_hover.png"))
	_theme.set_stylebox("pressed", "Button", _box("res://assets/sprites/ui_button_pressed.png"))
	_theme.set_stylebox("disabled", "Button", _box("res://assets/sprites/ui_button_disabled.png"))
	_theme.set_stylebox("focus", "Button", _box("res://assets/sprites/ui_button_hover.png"))
	_theme.set_color("font_color", "Button", Color(0.92, 0.88, 0.78))
	_theme.set_color("font_hover_color", "Button", Color(0.54, 1.0, 0.94))
	_theme.set_color("font_pressed_color", "Button", Color(1.0, 0.62, 0.24))
	_theme.set_color("font_focus_color", "Button", Color(0.54, 1.0, 0.94))
	_theme.set_color("font_disabled_color", "Button", Color(0.46, 0.45, 0.42))
	# OptionButton + its dropdown reuse the button/panel skin.
	for state in ["normal", "hover", "pressed", "disabled", "focus"]:
		_theme.set_stylebox(state, "OptionButton", _theme.get_stylebox(state, "Button"))
	for col in ["font_color", "font_hover_color", "font_pressed_color", "font_focus_color", "font_disabled_color"]:
		_theme.set_color(col, "OptionButton", _theme.get_color(col, "Button"))
	_theme.set_stylebox("panel", "PopupMenu", _box("res://assets/sprites/ui_panel.png", 8.0))
	_theme.set_color("font_color", "PopupMenu", Color(0.92, 0.88, 0.78))
	_theme.set_color("font_hover_color", "PopupMenu", Color(0.54, 1.0, 0.94))
	var hl := StyleBoxFlat.new()
	hl.bg_color = Color(0.12, 0.34, 0.32)
	_theme.set_stylebox("hover", "PopupMenu", hl)
	# Sliders: dark groove, cyan fill.
	var groove := StyleBoxFlat.new()
	groove.bg_color = Color(0.035, 0.032, 0.03)
	groove.set_content_margin_all(3.0)
	_theme.set_stylebox("slider", "HSlider", groove)
	var fill := StyleBoxFlat.new()
	fill.bg_color = Color(0.24, 0.86, 0.8)
	fill.set_content_margin_all(3.0)
	_theme.set_stylebox("grabber_area", "HSlider", fill)
	_theme.set_stylebox("grabber_area_highlight", "HSlider", fill)
	return _theme


static func _box(path: String, content_margin: float = 10.0) -> StyleBoxTexture:
	var b := StyleBoxTexture.new()
	b.texture = load(path)
	b.set_texture_margin_all(TEXTURE_MARGIN)
	b.set_content_margin_all(content_margin)
	return b
