extends RefCounted
## Shared UI skin: riveted-metal 9-patch panels and buttons generated by
## tools/generate_ps1_sprites.gd. Call UiTheme.make() and assign to the root
## Control (also set its texture_filter to NEAREST so the patches stay chunky).

const TEXTURE_MARGIN := 15.0  # 5 logical px at the 3x sprite scale

static var _theme: Theme


static func make() -> Theme:
	if _theme != null:
		return _theme
	_theme = Theme.new()
	# Tile the panel's stretch zones: its grime stays pixel-scale on any size.
	var panel_box := _box("res://assets/sprites/ui_panel.png", 18.0)
	panel_box.axis_stretch_horizontal = StyleBoxTexture.AXIS_STRETCH_MODE_TILE
	panel_box.axis_stretch_vertical = StyleBoxTexture.AXIS_STRETCH_MODE_TILE
	_theme.set_stylebox("panel", "PanelContainer", panel_box)
	_theme.set_stylebox("normal", "Button", _box("res://assets/sprites/ui_button.png"))
	_theme.set_stylebox("hover", "Button", _box("res://assets/sprites/ui_button_hover.png"))
	_theme.set_stylebox("pressed", "Button", _box("res://assets/sprites/ui_button_pressed.png"))
	_theme.set_stylebox("disabled", "Button", _box("res://assets/sprites/ui_button_disabled.png"))
	_theme.set_stylebox("focus", "Button", _box("res://assets/sprites/ui_button_hover.png"))
	_theme.set_color("font_color", "Button", Color(0.92, 0.88, 0.78))
	_theme.set_color("font_hover_color", "Button", Color(0.54, 1.0, 0.94))
	_theme.set_color("font_pressed_color", "Button", Color(1.0, 0.62, 0.24))
	_theme.set_color("font_focus_color", "Button", Color(0.54, 1.0, 0.94))
	_theme.set_color("font_disabled_color", "Button", Color(0.46, 0.45, 0.42))
	# OptionButton + its dropdown reuse the button/panel skin.
	for state in ["normal", "hover", "pressed", "disabled", "focus"]:
		_theme.set_stylebox(state, "OptionButton", _theme.get_stylebox(state, "Button"))
	for col in ["font_color", "font_hover_color", "font_pressed_color", "font_focus_color", "font_disabled_color"]:
		_theme.set_color(col, "OptionButton", _theme.get_color(col, "Button"))
	_theme.set_stylebox("panel", "PopupMenu", _box("res://assets/sprites/ui_panel.png", 8.0))
	_theme.set_color("font_color", "PopupMenu", Color(0.92, 0.88, 0.78))
	_theme.set_color("font_hover_color", "PopupMenu", Color(0.54, 1.0, 0.94))
	var hl := StyleBoxFlat.new()
	hl.bg_color = Color(0.12, 0.34, 0.32)
	_theme.set_stylebox("hover", "PopupMenu", hl)
	# Sliders: dark groove, cyan fill.
	var groove := StyleBoxFlat.new()
	groove.bg_color = Color(0.035, 0.032, 0.03)
	groove.set_content_margin_all(3.0)
	_theme.set_stylebox("slider", "HSlider", groove)
	var fill := StyleBoxFlat.new()
	fill.bg_color = Color(0.24, 0.86, 0.8)
	fill.set_content_margin_all(3.0)
	_theme.set_stylebox("grabber_area", "HSlider", fill)
	_theme.set_stylebox("grabber_area_highlight", "HSlider", fill)
	return _theme


static func setup_overlay(o: Control) -> void:
	## Styles a Control as a hidden fullscreen overlay: themed, nearest-filtered,
	## with a dimming backdrop. Used by every in-run modal panel.
	## Anchors AND offsets are forced so this also works on controls that are
	## already inside the tree (e.g. a panel styling itself in _ready).
	o.theme = make()
	o.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	o.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	o.visible = false
	var dim := ColorRect.new()
	dim.color = Color(0, 0, 0, 0.6)
	dim.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	o.add_child(dim)


static func overlay(parent: Node) -> Control:
	var o := Control.new()
	setup_overlay(o)
	parent.add_child(o)
	return o


static func center_panel(overlay_node: Control) -> VBoxContainer:
	## Centered riveted-metal panel inside an overlay; returns its content box.
	var center := CenterContainer.new()
	center.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	overlay_node.add_child(center)
	var panel := PanelContainer.new()
	center.add_child(panel)
	var margin := MarginContainer.new()
	for side in ["margin_left", "margin_right", "margin_top", "margin_bottom"]:
		margin.add_theme_constant_override(side, 24)
	panel.add_child(margin)
	var box := VBoxContainer.new()
	box.add_theme_constant_override("separation", 14)
	margin.add_child(box)
	return box


static func focus_when_ready(control: Control) -> void:
	_grab_focus_if_ready.call_deferred(control)


static func _grab_focus_if_ready(control: Control) -> void:
	if is_instance_valid(control) and not control.is_queued_for_deletion() \
			and control.is_inside_tree() and control.is_visible_in_tree():
		control.grab_focus()


static func _box(path: String, content_margin: float = 10.0) -> StyleBoxTexture:
	var b := StyleBoxTexture.new()
	b.texture = load(path)
	b.set_texture_margin_all(TEXTURE_MARGIN)
	b.set_content_margin_all(content_margin)
	return b
